### ISSUE TITLE
Get ftw command-line published on pip

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/ftw-baselines#3]
It's always nicer to not require people to clone a repo, and pip provides a more public place for the tools. So would be good to get that working.

**Comment by m-mohr** [comment]
We need to resolve the issue that some pip packages are instaleld via pyproject.toml and some via the conda env. That should probably all be installed via pyproject.toml... We should also indicate what the conda env actually installs so that people installing the pip version know what else they need. (env.yaml will not be installed via pip and users would see errors.)

**Comment by m-mohr** [comment]
https://pypi.org/project/ftw-tools/
