### ISSUE TITLE
inference polygonize: allow for export as shapefile

### ISSUE THREAD

**Issue by tristangrupp** [fieldsoftheworld/ftw-baselines#70]
This function "command_parquet" allows parquet, geojson, gpkg... but not shapefile. Could it be potentially modified to export shapefiles as well? I personally prefer ArcGIS to QGIS

**Comment by m-mohr** [comment]
I guess you meant the inference polygonize command?

Shapefiles don't really work well with fiboa due to the limited data types, no metadata in headers and the column name length restrictions.

Is there no way to make ArcGIS use any state-of-the-art file format (which is any format that is not a Shapefile)? :-)

PS: I heard that ArcGIS recently added support for duckdb, which supports GeoParquet. Maybe that helps to bridge it for now?

**Comment by tristangrupp** [comment]
Yup, the function to create polygons from the inference. Sorry for the mislabel. 

I totally understand the issues with shapefiles limits, but do those limits apply to a simple raster to polygon result?
It'd be great if ESRI moved away from shapefiles, but it does use them.
I can look into duckDB if adding shapefile as an export option is not possible, or just do the conversion step on my own

**Comment by cholmes** [comment]
Yeah, DuckDB can export shapefile. But I'm fairly against supporting shapefile. What version of ArcGIS are you using? I'm pretty sure most versions of ArcGIS now support GeoPackage.
